eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5

spring:
  redis:
    host: 10.68.61.35
    password: tclplus2020
    port: 6379
    timeout: 500
    pool:
      min-idle: 1
      max-idle: 8
      max-active: 8
  jpa:
    hibernate:
      ddl-auto: update
  shardingsphere:
    props:
      sql:
        show: true
    masterslave:
      #策略
      load-balance-algorithm-type: round_robin
      name: ds_ms
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave
    datasource:
      names: ds-master,ds-slave
      #主库
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.68.61.34:3306/tclplus?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: admin_user
        password: admin_user
        #从库
      ds-slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.68.61.34:3306/tclplus?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: admin_user
        password: admin_user

#发送邮件
send:
  account:
    username: vip_server_china@tcl.com
    password:
    host: mail.tcl.com
    port: 25
  validcode:
  sendInterval: 60
  validInterval: 1800
  smtp:
    timeout: 5000
    connectionTimeout: 5000
    writeTimeout: 5000

#日志文件路径定义:/tmp/log/微服务名称
logging:
  file:
    path: /tmp/log/service-advert