eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5

spring:
#  servlet:
#    multipart:
#        enabled: true
#        max-file-size: 20MB # 单个文件的最大值
#        max-request-size: 100MB # 上传文件总的最大值
  redis:
    host: 10.68.61.35
    port: 6379
    password: tclplus2020
    timeout: 500ms
    pool:
      min-idle: 1
      max-idle: 8
      max-active: 8
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  shardingsphere:
    masterslave:
      #策略(轮询)
      load-balance-algorithm-type: round_robin
      name: ds_ms
      master-data-source-name: dsmaster
      slave-data-source-names: dsslave
    datasource:
      names: dsmaster,dsslave
      #主库
      ds_master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.68.61.34:3306/tclplus?autoReconnect=true&useSSL=false
        username: admin_user
        password: admin_user
      #从库
      ds_slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.68.61.34:3306/tclplus?autoReconnect=true&useSSL=false
        username: admin_user
        password: admin_user

#tclaccounnt:
  #url: https://account-dev.tcljd.com
#日志文件路径定义:/tmp/log/微服务名称
logging:
  file:
    path: /tmp/log/service-points