server:
  port: 8100

spring:
  application:
    name: gateway
  profiles:
    active: dev

#management:
#  security:
#    enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

ehcache:
  resource:
    # max memory , unit-MB
    heap:
      size : 100
  ehcache:
    expired:
      default:
        age : 100.00

enable.tangram.default.data : true
logging.level.org.springframework.cloud.gateway: info
