eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5


spring:
  datasource:
    url: jdbc:mysql://10.68.61.34:3306/tclplus?useSSL=false
    username: admin_content
    password: admin_content
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 10.68.61.35
    password: tclplus2020
    port: 6379
    timeout: 500ms
    pool:
      min-idle: 1
      max-idle: 8
      max-active: 8
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE  #加上这个就可以获取到HttpServletRequest
#          thread:
#            timeoutInMilliseconds: 10000

tcl:
  account:
    publicKey: https://account-dev.tcljd.com/auth/common/publicKey








