spring:
  application:
    name: service-scheduler
  profiles:
    active: dev

server:
  port: 8007

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

management:
  security:
    enabled: false
