spring:
  application:
    name: service-version
  profiles:
    active: dev
server:
  port: 8009

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

management:
  security:
    enabled: false
